require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
Metrics/BlockLength:
  Exclude:
  - 'Rakefile'
  - 'spec/**/*.rb'
Metrics/MethodLength:
  Max: 15
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/SymbolArray:
  EnforcedStyle: brackets
